name: job-analyzer
services:
  app:
    build: app/
    ports:
      - "8501:8501"
    volumes:
      - ./models/Vikhr-Llama-3.2-1B-Instruct:/app/models/Vikhr-Llama-3.2-1B-Instruct
      - ./models/jina-embeddings-v3:/app/models/jina-embeddings-v3
      
volumes:
  model_weights:
    external: true